### ISSUE TITLE
comrade matrix

### ISSUE THREAD

**Issue by jverzani** [jverzani/SpecialPolynomials.jl#23]
In https://discourse.julialang.org/t/gathering-monomial-coefficients-of-orthogonal-polynomials-using-specialpolynomials-jl/63554 the question of finding the comrade matrix came up. This matrix is like the companion matrix for orthogonal polynomials.

**Comment by BambOoxX** [comment]
@jverzani Sorry for the trouble, but I opened another issue there https://github.com/jverzani/AMRVW.jl/issues/8. Do you want me to close that one a move its contents here ?

**Comment by jverzani** [comment]
Hi @BambOoxX,

The most recent check in includes the unexported `comrade_pencil` which returns `C0` and `C1`, where `lambda*C1 - C0` is the pencil. If you upgrade `Polynomials` to its most recent release, then the block comrade matrix is available with the following syntax:

```
julia> using Polynomials, SpecialPolynomials, StaticArrays

julia> A = SA[1 0;2 1.0]
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 1.0  0.0
 2.0  1.0

julia> p = Legendre([A^0, A, A^2, A^3])
Legendre([1.0 0.0; 0.0 1.0]⋅P₀(x) [1.0 0.0; 2.0 1.0]⋅P₁(x) [1.0 0.0; 4.0 1.0]⋅P₂(x) [1.0 0.0; 6.0 1.0]⋅P₃(x))

julia> SpecialPolynomials.comrade_matrix(p)
6×6 Matrix{Float64}:
 0.0  0.0  0.333333  0.0       -0.6   0.0
 0.0  0.0  0.0       0.333333   3.6  -0.6
 1.0  0.0  0.0       0.0       -0.2   0.0
 0.0  1.0  0.0       0.0        2.4  -0.2
 0.0  0.0  0.666667  0.0       -0.6   0.0
 0.0  0.0  0.0       0.666667   1.2  -0.6
```

(That is, `comrade_matrix` forms the block comrade matrix if `p` has matrix coefficients. The use of StaticArrays is needed here, though before merging I'll try and work around that, it seems technical, not critical.)

I kind of lost track of exactly what you are after, but here is what this PR implements:

* if you have a polynomial with coefficients with `T <: Number`, then `roots(p)` will form the comrade matrix and solve via the algorithm of Aurentz, Vandrebril, and Watkins
* if you have  polynomial with coefficients `T <: Number` or `T <: Matrix{<:Number}` then `SpecialPolynomials.comrade_matrix(p)` will return a matrix; using `LinearAlgebra.eigvals` will find the eigenvalues.
*  if you have  polynomial with coefficients `T <: Number` or `T <: Matrix{<:Number}` then `SpecialPolynomials.comrade_pencil(p)` will return matrices `C0` and `C1` with `lambda*C1-C0` the pencil, which is the linearization I believe you were after.

If you are interested in an LU decomposition of the comrade matrix, this could be added, the recipe is in the paper of Amiraslania, Corless, and Lancaster.

**Comment by BambOoxX** [comment]
That is really nice ! What I am really working on is using the eigenvalues and vectors of the matrix, son an LU decomposition could be nice indeed. I still did not manage a justification regarding the lower precision of the comrade matrix vs companion matrix computation of roots though. Unless I messed something in my code, it still seems more precise to convert the polynomial to its monomial from then compute the roots using the companion matrix...

**Comment by BambOoxX** [comment]
@jverzani I just tested your code. I could not obtain it via the `Polynomials` update, but I coy pasted the relevant parts in a file. 
It  actually allowed me to correct my implementation of the comrade pencil, which suffered from collisions between notations used in different articles... 
I have a question regarding your current implementation. Why do you recompute the `\alpha,\beta,\gamma` ? they seem to be what is already accessible through `SpecialPolynomials.an,bn,cn` ?

**Comment by jverzani** [comment]
The alpha, beta, gamma need not be specific to orthogonal polynomials, whereas the An, Bn, Cn are. So this gives some flexibility if someone wanted to find the comrade pencil for standard basis polynomials or Newton polynomials. (I was kind of curious to see how this algorithm compared to the one in AMRVW which is for standard basis polynomials, though haven't scratched that itch yet...).

**Comment by jverzani** [comment]
I just pushed a commit that computes an LU decomposition of the comrade pencil.

I think for now, that is it, unless there is something else  you were looking for. I found this [paper](https://arxiv.org/pdf/1611.10142.pdf) which has a more efficient way of computing eigenvalues of block companion matrices. Somehow I overlooked this work when doing the AMRVW.jl package. So when I get a chance will look at adding that. Maybe there is similar work for the block comrade matrix.

**Comment by BambOoxX** [comment]
@jverzani This is really much more than I could have hoped for. Thank you very much. I have to say a clean and robust root-finding algorithm (beyond standard eigensolvers) would be great for this case, and I don't think it exists at the moment in the julia ecosystem. 
I don't know if / when you'd have time for this, but if you need help or just someone to test the code, just let me know.
