### ISSUE TITLE
Depend on IntervalSets.jl rather than Intervals.jl?

### ISSUE THREAD

**Issue by johnbcoughlin** [jverzani/SpecialPolynomials.jl#38]
(This is an exact copy of a similar [issue](https://github.com/JuliaMath/Polynomials.jl/issues/374) I just filed with Polynomials.jl)

There are two packages in the ecosystem for representing operations on non-iterable intervals, IntervalsSets.jl and Intervals.jl.

The latter currently depends on TimeZones.jl directly, which is a heavy transitive dependency for pure-math projects which want to use SpecialPolynomials. (I've opened an issue to address this). It is not as light-weight and includes functionality for plotting and printing intervals, as well as anchored intervals. Finally, it is not as widely used in the math ecosystem. See below for the list of each package's dependees.

For all these reasons, it would be nice to switch to using IntervalSets. Unfortunately, this will be a breaking change. What are the thoughts of the core maintainers on this, and would it be something that you'd consider addressing in a future breaking release?

```
julia> direct_dependents("Intervals")
10-element Vector{String}:
 "ConstraintDomains"
 "DateSelectors"
 "EconoSim"
 "Empirikos"
 "IndependentHypothesisWeighting"
 "LibPQ"
 "PatternFolds"
 "Polynomials"
 "SoapySDR"
 "SpecialPolynomials"

julia> direct_dependents("IntervalSets")
53-element Vector{String}:
 "AbstractPlotting"
 "ApproxFun"
 "ApproxFunBase"
 "ApproxFunFourier"
 "ApproxFunOrthogonalPolynomials"
 "ApproxFunSingularities"
 "AxisArrays"
 "AxisIndices"
 "AxisKeys"
 "BAT"
 "BasicBSpline"
 "CalculusWithJulia"
 "CamiXon"
 "ClassicalOrthogonalPolynomials"
 "ClimaCore"
 "CompactBases"
 "ComplexPhasePortrait"
 "ContinuumArrays"
 "CoulombIntegrals"
 "DirectionalStatistics"
 "DomainIntegrals"
 "DomainSets"
 "DungAnalyse"
 "DungBase"
 ⋮
 "InventoryManagement"
 "Khepri"
 "Makie"
 "MartaCT"
 "MeasureTheory"
 "OrthogonalPolynomialsQuasi"
 "PICDataStructures"
 "Poltergeist"
 "ProfileView"
 "RadiationDetectorSignals"
 "RadiationSpectra"
 "RayTracing"
 "ReinforcementLearningEnvironments"
 "ReinforcementLearningExperiments"
 "ReinforcementLearningZoo"
 "SampledSignals"
 "SolidStateDetectors"
 "StaticRanges"
 "StatsDiscretizations"
 "StatsMakie"
 "TimeAxes"
 "ValueShapes"
 "YAXArrays"
```

**Comment by jverzani** [comment]
#41 puts this in place. I just need to merge in https://github.com/JuliaMath/Polynomials.jl/pull/381.
