### ISSUE TITLE
Typo in generating function for Laguerre polinomials

### ISSUE THREAD

**Issue by Yaraslaut** [jverzani/SpecialPolynomials.jl#39]
There is such generation function in Laguerre.jl.

``
generating_function(::Type{<:Laguerre{α}}) where {α} =
    (t, x) -> begin
        exp(-t * x / (1 - t)) / (1 - t)^(α - 1)
    end
``

While definition of generation function of Laguerre polinomials in [here](https://mathworld.wolfram.com/AssociatedLaguerrePolynomial.html)  or [here](https://en.wikipedia.org/wiki/Laguerre_polynomials#Generalized_Laguerre_polynomials) given by
`
exp(-t * x / (1 - t)) / (1 - t)^(α + 1)
`

**Comment by jverzani** [comment]
Oops. Thanks for letting me know I messed this up!! I'll post a fix today.
