### ISSUE TITLE
Makie.jl to plot 

### ISSUE THREAD

**Issue by mora200217** [jverzani/SpecialPolynomials.jl#82]
I want to plot in the same manner as with `Plots.jl` but with `Makie.jl` For example, take a Legendre polynomial and just with lines!(), plot the polynomial.

```julia
using CairoMakie, SpecialPolynomials, Polynomials

Pln = Legendre([0 0 0 1])
lines(Pln)
```
However, when running this try, there is this error

``` bash

ERROR: ArgumentError:     Conversion failed for Lines (With conversion trait PointBased()) with args: Tuple{Legendre{Int64, :x}} 
```
Is there a way to do this ? I heard that using recipes, but is nothing implemented yet ? 

**Julia:** v1.10
**Makie** -> CairoMakie

**Comment by jverzani** [comment]
Hmm, there is an extension for MakieCore that should already do this. I'll have to look and see if something has changed on the Makie side.

**Comment by mora200217** [comment]
Oh really? That would be nice! I did not know about it. If you find any doc that could help me, I would appreciate it ! :D

**Comment by jverzani** [comment]
It isn't really documented, sorry. But this should work with Makie and SpecialPolynomials loaded:

```
julia> Pln = Legendre([0 0 0 1])
Legendre(1⋅P₃(x))

julia> plot(Pln)
```

**Comment by mora200217** [comment]
I did try that, but there is kind of an Error on the make recipe. I'm either using CairoMakie or GLMakie. Do I have to import the Makie dependencies ? 

For 
```julia
using SpecialPolynomials, GLMakie
Pln = Legendre([0 0 0 1])
plot(Pln)
```
**Output:** 
```
ERROR: No recipe for plot with args: Tuple{Legendre{Int64, :x}}
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] plot!
   @ ~/.julia/packages/Makie/rEu75/src/interfaces.jl:353 [inlined]
 [3] connect_plot!(parent::Scene, plot::Plot{MakieCore.plot, Tuple{Legendre{Int64, :x}}})
   @ Makie ~/.julia/packages/Makie/rEu75/src/interfaces.jl:380
 [4] plot!
   @ ~/.julia/packages/Makie/rEu75/src/interfaces.jl:389 [inlined]
 [5] plot!(ax::Axis, plot::Plot{MakieCore.plot, Tuple{Legendre{Int64, :x}}})
   @ Makie ~/.julia/packages/Makie/rEu75/src/figureplotting.jl:412
 [6] plot!(fa::Makie.FigureAxis, plot::Plot{MakieCore.plot, Tuple{Legendre{Int64, :x}}})
   @ Makie ~/.julia/packages/Makie/rEu75/src/figureplotting.jl:407
 [7] _create_plot(F::Function, attributes::Dict{Symbol, Any}, args::Legendre{Int64, :x})
   @ Makie ~/.julia/packages/Makie/rEu75/src/figureplotting.jl:318
 [8] plot(args::Legendre{Int64, :x})
   @ MakieCore ~/.julia/packages/MakieCore/f3yyf/src/recipes.jl:39
 [9] top-level scope
   @ REPL[3]:1
```

Environment: 
- Julia v1.10.4
- SpecialPolynomials v0.4.9
- Polynomials v3.2.4
- GLMakie v0.10.5
- Makie v0.21.5

**Comment by jverzani** [comment]
Oddly, what was working for me this AM is not not. I have to take a deeper dive. Sorry.

**Comment by jverzani** [comment]
Thanks for this issue. Turns out SpecialPolynomials needed a bit of love (the compatability bounds needed fixing). Hopefully when you upgrade to the next version (which I am just registering) this will work as expected.

**Comment by mora200217** [comment]
Thank you very much! It was a version issue. I will close this thread. Thanks again!
